---
output: html_document
---

```{css, echo=FALSE}
h5 {text-align: center;}
```

```{r, include=FALSE, message=FALSE, warning=FALSE}
# Installing and loading required packages

if (!require("tidyverse"))
  install.packages("tidyverse")
if (!require("tidycensus"))
  install.packages("tidycensus")
if (!require("sf"))
  install.packages("sf")
if (!require("mapview"))
  install.packages("mapview")
if (!require("DataEditR"))
  install.packages("DataEditR")
if (!require("leaflet"))
  install.packages("leaflet")
if (!require("leaflet.extras2"))
  install.packages("leaflet.extras2")
if (!require("plotly"))
  install.packages("plotly")
if (!require("gtExtras"))
  install.packages("gtExtras")

library(tidyverse)
library(tidycensus)
library(sf)
library(mapview)
library(DataEditR)
library(leaflet)
library(leafpop)
library(plotly)
library(gtExtras)

# Reading files from local computer project folder

TNSenateMap <- st_read("TNSenateMap.shp")
TNSenateData <- read_csv("TNSenateRaceData.csv")

# Edit / update election data

TNSenateData <- data_edit(TNSenateData)
write_csv(TNSenateData,"TNSenateRaceData.csv")
write_csv(TNSenateData,"TNSenateRaceData_latest.csv")

# Merge election and map data

TNSenateWinners <- merge(TNSenateMap,TNSenateData)

# Make the election map

mypalette = colorRampPalette(c("gray","darkblue","darkred"))

# Use this palette if an independent wins
# mypalette = colorRampPalette(c("gray","#384B70","#B8001F","#FFD35A"))

TNSenateElectionMap <-
  mapview(
  TNSenateWinners,
  zcol = "Party",
  col.regions = mypalette,
  alpha.regions = .8,
  layer.name = "Party",
  popup = popupTable(
    TNSenateWinners,
    feature.id = FALSE,
    row.numbers = FALSE,
    zcol = c(
      "District",
      "Party",
      "Dem",
      "Rep",
      "Ind"
    )
  )
)

# Seats by party

TNSenateWinnersTable <- TNSenateData %>% 
  group_by(Party) %>% 
  summarize(Seats = n()) %>% 
  gt() %>% 
  cols_align(align = "center") %>% 
  gt_theme_538

# Show the map

TNSenateElectionMap

# Show the table

TNSenateWinnersTable

```

#### **Tennessee State Senate**

```{r, echo=FALSE}
TNSenateElectionMap
```

##### <br> <br> <br> <br> <br> <br> <br> **Seats by party**

```{r, echo=FALSE}
TNSenateWinnersTable
```
